### ISSUE TITLE
how it works

### ISSUE THREAD

**Issue by conradKE** [muhannad0/mikrotik-traffic-counter#2]
how does this work

**Comment by muhannad0** [comment]
Hi @azim254 

In summary, you need to do the following to make this work.

1. Host the PHP files on a webserver that the Mikrotik router can access it.
2. Create the firewall rules and script on the Mikrotik router to collect the required stats. Set the script to be run on a schedule that will upload the stats to the webserver.
3. You can visit the webserver to see the graphs after some time.

The detailed steps are on the project README. The additional links at the bottom can explain in detail what is going on.
