### ISSUE TITLE
Hi very good and interesting project but i have a question/doubt

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [muhannad0/mikrotik-traffic-counter#3]
Hi first of all thank you very much for your project its something i will give it a test for my own project.

but i have a question i see init.php sqlite, do i need to create a database? i am using mysqli with php7 on my server test machine.

if so is there any .sql files missing? or does de INIT genera the sqlite tables automátically?

also i am planning to log traffic from mikrotik device via WAN.. on static IP.. so i guess i will have to modify the firewall mangle rules also?

**Comment by muhannad0** [comment]
Hi @AlbertEinsteinGlitchPoint

No, you don't need to create a database. The `init.php` script will create a sqlite database file (along with the required tables) in the same directory if it doesn't exist.

However, if you want to use an external SQL database, then you may need to modify the `collector` and `index` PHP scripts to use the external DB. The table structures would be the same as defined in `init.php`

As for creating the Mikrotik firewall mangle rules, you can change the command's `src/dst-address` and `in/out-interface` values that matches your router's configuration.
