### ISSUE TITLE
Bytes/Bits question

### ISSUE THREAD

**Issue by apollie** [muhannad0/mikrotik-traffic-counter#4]
Hello! Thanks for this project!
However i am confused with the right metrics units.
Mikrotik sends data as BYTES, also this data is inserted to sqlite as is.
But in index.php the units are defined as `Mb`, which translates to MegaBits, and i don't find anywhere in the code where the conversion happens.
So to me it looks like a typo, and has to be changed to `MB`.
Is it so? Could you please check?

**Comment by muhannad0** [comment]
Hello. Yes, you are right. The code uses the raw data from the device.

Unfortunately, I'm not actively maintaining this project now since I have moved away from Mikrotik devices at work. So I don't have the necessary equipment to tinker with. So feel free to fork and update it to your liking.
