### ISSUE TITLE
IP Firewall mangle

### ISSUE THREAD

**Issue by ilexpl01** [muhannad0/mikrotik-traffic-counter#5]
Hi,

I was wondering why You mangle forward chain for upload and download.

Why not to mangle as below ?

3    ;;; local-wan-Toya-tx
      chain=postrouting action=passthrough src-address-list=MyIPAddresses out-interface=ether1 log=no log-prefix="" 

 4    ;;; local-wan-Toya-rx
      chain=prerouting action=passthrough in-interface=ether1 log=no log-prefix="" 

 5    ;;; local-wan-LTE-tx
      chain=postrouting action=passthrough src-address-list=MyIPAddresses out-interface=ether2 log=no log-prefix="" 

 6    ;;; local-wan-LTE-rx
      chain=prerouting action=passthrough in-interface=ether2 log=no log-prefix="" 

[admin@MikroTik] /ip/firewall/address-list> print
Columns: LIST, ADDRESS, CREATION-TIME
# LIST                ADDRESS           CREATION-TIME       
0 PrivateIPAddresses  192.168.0.0/16    jul/12/2022 11:53:13
1 PrivateIPAddresses  172.16.0.0/12     jul/12/2022 11:55:46
2 PrivateIPAddresses  10.0.0.0/8        jul/12/2022 11:56:15
3 MyIPAddresses       192.168.100.0/24  jul/16/2022 20:00:21

I have two ISP's connercted to ether1 & ether2.

I was not able to find any other examples with monitoring upload/download on MikroTik.

**Comment by muhannad0** [comment]
Hello there.

I'm not actively maintaining this project now since I have moved away from Mikrotik devices at work. So I don't have the necessary equipment to tinker with. So feel free to fork and update it to your liking.
